<a href="https://colab.research.google.com/github/gabie0208/eee4178-deep-learning/blob/main/1103_basic_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.1 자료형과 연산


숫자형

In [1]:
a = 10
b = 1.2
print(a, b)
print(a+b, a-b, a*b, a/b)

10 1.2
11.2 8.8 12.0 8.333333333333334



문자형

In [2]:
quote = "Life is too short,"
print(quote, "You need Python")

Life is too short, You need Python


In [4]:
odd = [1, 3, 5, 7, 9]
alphabet = ["abc", "def", "ghi"]
empty = []

odd[1]

3

리스트

In [5]:
print("alphabet[0]: ", alphabet[0])
print("odd[-1]: ", odd[-1])
print("odd[0:2]: ", odd[0:2])

alphabet[0]:  abc
odd[-1]:  9
odd[0:2]:  [1, 3]


In [6]:
alphabet.append("A")
alphabet.append(["B", "c"])
print(alphabet)

['abc', 'def', 'ghi', 'A', ['B', 'c']]


In [7]:
empty.append(1)
empty.append(2)
empty.append('3')
empty

[1, 2, '3']

In [8]:
print(type(empty[0]))
print(type(empty[-1]))

<class 'int'>
<class 'str'>


튜플


list와 비슷하지만 요소값 생성, 삭제, 수정이 불가


()로 묶여 있음 (list의 경우 [])

In [9]:
t = (1, "sogang", 2, 3.5)
t

(1, 'sogang', 2, 3.5)

In [10]:
type(t)

tuple

In [11]:
print(t[0])
print(t[1])

1
sogang


In [13]:
t = t + (4, "university")
t

(1, 'sogang', 2, 3.5, 4, 'university', 4, 'university')

In [14]:
t*2

(1,
 'sogang',
 2,
 3.5,
 4,
 'university',
 4,
 'university',
 1,
 'sogang',
 2,
 3.5,
 4,
 'university',
 4,
 'university')

In [16]:
t2 = ((1, 2), ("sogang", 3), ("university, 4"))
print(t2[1])
print(t2[1][1])

('sogang', 3)
3


딕셔너리


Key와 Value를 한 쌍으로 갖는 자료형

In [17]:
# Dictionary: {Key1:Value1, Key2:Value2, Key3:Value3, ....}

dic = {"김철수":80, "이영희":90, "박아무개":85}
print(dic)
print(dic["김철수"])
print(dic.keys())
print(dic.values())

{'김철수': 80, '이영희': 90, '박아무개': 85}
80
dict_keys(['김철수', '이영희', '박아무개'])
dict_values([80, 90, 85])


In [18]:
dic["이름"]=100
print(dic)

{'김철수': 80, '이영희': 90, '박아무개': 85, '이름': 100}


### 1.2 제어문


if문

In [19]:
print('emtpy:',empty)

if empty[1]%2 == 0:
  print("{} is an even number".format(empty[1]))
elif empty[1]%2 == 1:
  print("{} is an odd number".format(empty[1]))
else:
  print("Impossible")

emtpy: [1, 2, '3']
2 is an even number


for문

In [20]:
for i in range(5):
  print(i)

0
1
2
3
4


while문


In [21]:
start = 0
while start<5:
  print(start)
  start = start + 2

print("final value: {}".format(start))

0
2
4
final value: 6


### 1.3 함수/클래스


함수

In [22]:
def square_sum(a,b):
  squared_a = a**2
  squared_b = b**2
  
  return squared_a + squared_b

c = square_sum(3,4)
print("squared sum of {} and {} : {}".format(3, 4, c))

squared sum of 3 and 4 : 25


In [23]:
class Calculator():
  def __init__(self):
    self.description = "Example for initalizing a Class"
    self.result = 0

  def add(self, num1, num2):
    if type(num1) == int and type(num2) == int :
      result = num1 + num2
      return result
    else:
      raise Exception

  def mul(self, num1, num2):
    if type(num1) == int and type(num2) == int :
      result = num1 * num2
      return result
    else:
      raise Exception

cal = Calculator()
print(cal.description)
print(cal.add(3,4))
print(cal.mul(3,4))

Example for initalizing a Class
7
12


### 1.4 패키지


import


In [24]:
import numpy as np

array = np.array([1,2,3])
print(array, type (array))

[1 2 3] <class 'numpy.ndarray'>


### 2.1 Tensors / Numpy

In [25]:
import torch
import numpy as np

## colab의 경우, 대부분의 package install 필요 없음 (바로 import 가능)
## 패키지 설치가 필요할 경우: 'pip install package_name'

Python List: 행렬 연산을 위해 for 문 사용


Numpy : 차원이 다른 행렬 간에도 연산이 가능


Tensor : GPU 상에서 연산이 가능하고 autograd(자동 미분)연산 기능이 있는 자료형

Tensor 생성 및 초기화

In [26]:
# 초기화되지 않은 행렬 생성
x = torch.empty(5,3)
print(x)

tensor([[-1.2115e+27,  3.0822e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0822e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -2.8904e+26]])


In [27]:
# 0 ~ 1 사이의 랜덤 초기화 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.9621, 0.9549, 0.3893],
        [0.4465, 0.2410, 0.3692],
        [0.9784, 0.5608, 0.7741],
        [0.3612, 0.0879, 0.0427],
        [0.4114, 0.5857, 0.3959]])


In [28]:
x.mean()

tensor(0.5041)

In [29]:
x.std()

tensor(0.2990)

In [30]:
# Standard Normal Distribution에서 랜덤 초기화 행렬 생성
x = torch.randn(5,3)
print(x)

tensor([[ 1.2303, -0.1819, -1.7271],
        [ 2.6370, -0.4519,  0.2558],
        [-0.8972, -0.5797,  0.1359],
        [ 1.0862, -1.4128, -0.1379],
        [-0.5021, -0.4282, -1.4600]])


In [31]:
x.mean()

tensor(-0.1622)

In [32]:
x.std()

tensor(1.1427)

In [33]:
# 특정 값을 tensor로 만들기
x = torch.tensor([[1.2, 4.5],[1, 2]])
x

tensor([[1.2000, 4.5000],
        [1.0000, 2.0000]])

Tensor size & Numpy 변환

In [34]:
# Size 확인
x = torch.randn(3,4)
print(x)
print("x size : ", x.size())

tensor([[ 0.5655, -0.2939, -1.3205,  0.2901],
        [ 0.0637,  1.2894,  0.0183,  1.0282],
        [ 1.6469,  0.2537,  1.1846,  0.8440]])
x size :  torch.Size([3, 4])


In [35]:
# Resize - "reshape" : any tensor
x = torch.rand(3,4)
y = x.reshape(4,3)
z = x.reshape(-1, 2)
print(x, x.size(), "\n", y, y.size(), "\n", z, z.size())

tensor([[0.5065, 0.3122, 0.6880, 0.3119],
        [0.5502, 0.5931, 0.1235, 0.4649],
        [0.1532, 0.3244, 0.1812, 0.3019]]) torch.Size([3, 4]) 
 tensor([[0.5065, 0.3122, 0.6880],
        [0.3119, 0.5502, 0.5931],
        [0.1235, 0.4649, 0.1532],
        [0.3244, 0.1812, 0.3019]]) torch.Size([4, 3]) 
 tensor([[0.5065, 0.3122],
        [0.6880, 0.3119],
        [0.5502, 0.5931],
        [0.1235, 0.4649],
        [0.1532, 0.3244],
        [0.1812, 0.3019]]) torch.Size([6, 2])


In [36]:
# Resize - "view" : for contiguous tensors
x = torch.randn(3,4)
y = x.view(4,3)
z = x.view(-1, 2)
print(x, x.size(), "\n", y, y.size(), "\n", z, z.size())

tensor([[-0.8268,  0.2210,  1.0527,  0.8681],
        [ 0.2998,  1.6552,  0.6452,  0.4080],
        [-0.8007,  2.6310, -0.9569,  2.0408]]) torch.Size([3, 4]) 
 tensor([[-0.8268,  0.2210,  1.0527],
        [ 0.8681,  0.2998,  1.6552],
        [ 0.6452,  0.4080, -0.8007],
        [ 2.6310, -0.9569,  2.0408]]) torch.Size([4, 3]) 
 tensor([[-0.8268,  0.2210],
        [ 1.0527,  0.8681],
        [ 0.2998,  1.6552],
        [ 0.6452,  0.4080],
        [-0.8007,  2.6310],
        [-0.9569,  2.0408]]) torch.Size([6, 2])


In [37]:
# Tensor to numpy
x = torch.ones(5)
y = x.numpy()
print(x, type(x))
print(y, type(y))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [38]:
# Numpy to tensor
x = np.ones(5)
y = torch.from_numpy(x)
print(x, type(x))
print(y, type(y))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [39]:
# GPU 연산을 위한 CUDA tensor
x = torch.ones(5)
y = x.to(device="cuda:0") #런타임 연결 gpu로 설정
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], device='cuda:0')


Tensor Autograd


requires_grad를 true로 세팅하면 tensor에 대한 모든 연산 추적 가능


이를 통해 forward propagation 후, .backward() 호출 시 모든 gradient 자동으로 계산

In [40]:
x = torch.tensor(([1., 2.], [3., 4.]), requires_grad=True)
print(x)
y = (x+2) **2 *3
print(y)

out = y.mean()
print(out)

out.backward()
print(x.grad)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)
tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])
