<a href="https://colab.research.google.com/github/gabie0208/eee4178-deep-learning/blob/main/vector_matrix_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.1 수학과 파이썬 복습

### 벡터와 행렬

*   shape 다차원원 배열의 형상
*   ndim 차원 수



In [4]:
import numpy as np
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
W = np.array([[1,2,3], [4,5,6]])
W.shape

(2, 3)

In [9]:
W.ndim

2

## 행렬의 원소별 연산

In [10]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

## Broadcast

In [13]:
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [14]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

## 벡터의 내적과 행렬의 곱

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

# 4 + 10 + 18 = 32

32

In [16]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], 
              [7,8]])
np.matmul(a,b)

# (5+14), (6+16)
# (15+28), (18+32)

array([[19, 22],
       [43, 50]])

# 1.2 신경망 추론

In [18]:
W1 = np.random.randn(2,4) # weight
b1 = np.random.randn(4) # bias
x = np.random.randn(10,2) # input
h = np.matmul(x, W1) + b1
h

array([[-3.02015977, -0.70620814,  1.20481896,  2.90385907],
       [ 1.13953636, -0.68045318,  0.7513295 ,  0.98753806],
       [ 4.45189244, -0.86197496,  0.17517863, -1.0421635 ],
       [-0.82781526, -0.72334457,  0.93312212,  1.81729985],
       [ 1.78803445, -0.60541123,  0.75623019,  0.86588001],
       [ 0.86661339, -0.71456934,  0.74656938,  1.03241893],
       [-2.70572102, -0.90546637,  0.95637904,  2.25731906],
       [ 0.80843926, -0.9192258 ,  0.53546145,  0.54982962],
       [ 4.73673709, -0.71915265,  0.29426577, -0.82167422],
       [-1.46959291, -0.98943935,  0.72409055,  1.4593897 ]])

In [20]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

a = sigmoid(h)
a

array([[0.04652339, 0.33043724, 0.76938094, 0.94803688],
       [0.7575945 , 0.33616017, 0.67946832, 0.72860137],
       [0.98847782, 0.29692689, 0.543683  , 0.26073276],
       [0.30410722, 0.32665691, 0.71770827, 0.86024181],
       [0.85668613, 0.35310667, 0.68053471, 0.70388769],
       [0.70404053, 0.32858997, 0.67843072, 0.73738459],
       [0.06263661, 0.28792845, 0.72239624, 0.90528   ],
       [0.69177682, 0.28511567, 0.63075601, 0.63409606],
       [0.99130899, 0.3275796 , 0.57304014, 0.30540838],
       [0.1870045 , 0.27102283, 0.67350715, 0.81143931]])

In [21]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

x = np.random.randn(10,2) # input
W1 = np.random.randn(2, 4) # weight
b1 = np.random.randn(4) # bias
W2 = np.random.randn(4, 3) # weight
b2 = np.random.randn(3) # bias

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

In [22]:
h

array([[-3.14594389, -0.47711802,  0.53037136,  2.06110085],
       [-1.33015964,  1.65437651,  3.96796335,  2.96020778],
       [-1.42341885, -1.66378042, -1.78871464, -0.03158384],
       [ 0.41951163,  0.10576107,  1.0153909 ,  0.51943365],
       [ 4.43322256, -0.64556941, -0.88633524, -2.5081493 ],
       [-4.32917958,  1.11351314,  3.47202703,  4.2105163 ],
       [-3.47336332, -1.48637306, -1.17624704,  1.32530216],
       [-0.57334417,  0.143808  ,  1.22876722,  1.13266634],
       [ 0.27058493,  0.86422714,  2.35649737,  1.30246034],
       [ 2.33393298,  0.02304797,  0.58769709, -0.67158412]])

In [23]:
a

array([[0.0412514 , 0.38293289, 0.62956972, 0.8870645 ],
       [0.20913296, 0.83948167, 0.98143911, 0.95074373],
       [0.19412617, 0.15925517, 0.14323038, 0.4921047 ],
       [0.60336638, 0.52641565, 0.73407383, 0.62701532],
       [0.98826323, 0.34398865, 0.29186668, 0.07528886],
       [0.01300694, 0.75278349, 0.96988129, 0.98537826],
       [0.0300797 , 0.18446673, 0.23572766, 0.7900625 ],
       [0.36046553, 0.53589017, 0.77360274, 0.75633063],
       [0.5672365 , 0.70354307, 0.91344929, 0.78624876],
       [0.91164863, 0.50576174, 0.64283658, 0.33814222]])

In [24]:
s

array([[ 0.10584474, -0.31902645,  0.68355142],
       [ 0.51487362, -0.76160961,  0.98631821],
       [-0.47250473, -0.87605487,  0.99098087],
       [ 0.18323389, -0.95696258,  1.34390502],
       [-0.37695237, -1.73893967,  2.02791938],
       [ 0.49287625, -0.42153145,  0.89431805],
       [-0.31423028, -0.61028767,  0.45593301],
       [ 0.24222748, -0.67295776,  1.1223531 ],
       [ 0.41172596, -0.95789312,  1.22027401],
       [ 0.036517  , -1.36986813,  1.85181327]])

## 1.2.2 계층으로 클래스화 및 순전파 구현

In [41]:
class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [42]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[-3.41468901 -0.41782945 -1.56288705]
 [-3.28394813  0.14987844 -0.58933637]
 [-3.52621956  0.4185557  -0.63195559]
 [-3.70000975 -0.57580272 -1.97061089]
 [-3.05474549 -1.27503052 -1.80842679]
 [-3.73340604  0.12948995 -1.48428787]
 [-3.50028407  0.29691011 -0.76955411]
 [-3.52588893 -0.43536553 -1.7375168 ]
 [-3.29337459 -0.90570576 -1.84533775]
 [-3.53286962  0.47360351 -0.55682755]]


# 1.3 신경망 학습

In [44]:
# coding: utf-8

class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        self.x = x
        return out

    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx


class Softmax:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        self.out = softmax(x)
        return self.out

    def backward(self, dout):
        dx = self.out * dout
        sumdx = np.sum(dx, axis=1, keepdims=True)
        dx -= self.out * sumdx
        return dx


class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads = [], []
        self.y = None  # softmax의 출력
        self.t = None  # 정답 레이블

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = cross_entropy_error(self.y, self.t)
        return loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size

        return dx


class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx


class SigmoidWithLoss:
    def __init__(self):
        self.params, self.grads = [], []
        self.loss = None
        self.y = None  # sigmoid의 출력
        self.t = None  # 정답 데이터

    def forward(self, x, t):
        self.t = t
        self.y = 1 / (1 + np.exp(-x))

        self.loss = cross_entropy_error(np.c_[1 - self.y, self.y], self.t)

        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = (self.y - self.t) * dout / batch_size
        return dx


class Dropout:
    '''
    http://arxiv.org/abs/1207.0580
    '''
    def __init__(self, dropout_ratio=0.5):
        self.params, self.grads = [], []
        self.dropout_ratio = dropout_ratio
        self.mask = None

    def forward(self, x, train_flg=True):
        if train_flg:
            self.mask = np.random.rand(*x.shape) > self.dropout_ratio
            return x * self.mask
        else:
            return x * (1.0 - self.dropout_ratio)

    def backward(self, dout):
        return dout * self.mask


class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

## Repeat node

In [45]:
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)

In [46]:
dy = np.random.randn(N, D) # random gradient
dx = np.sum(dy, axis=0, keepdims=True) # back propagation

## Sum node

In [47]:
D, N = 8, 7
x = np.random.randn(N, D)
y = np.sum(x, axis=0, keepdims=True) # forward propagation

dy = np.random.randn(1, D) # random gradient
dx = np.repeat(dy, N, axis=0) # back propagation

In [50]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

# (0 + -2 + -6), (1 + 2 + 3)

x @ y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [53]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1, -1],
              [1, -1, 0]])

# 1 + -2 + -3
np.inner(x, y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [55]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

np.linalg.inv(x)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [56]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [57]:
y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

np.linalg.pinv(y)

array([[ 5.00000000e-01,  4.09730229e-17, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [58]:
np.linalg.pinv(y) @ y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 5.55111512e-17,  1.00000000e+00]])